version: "3.1"

services:
  database:
    image: mydb
    networks:
      - back-tier

  api:
    image: myapi
    networks:
      - front-tier
      - back-tier

  ui:
    image: myui
    ports:
      - "3000:3000"
    networks:
      - front-tier

networks:
  front-tier:
  back-tier:
